# Generated by Django 5.1.1 on 2024-11-07 12:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
   Post = apps.get_model('blog', 'post')
   for post in Post.objects.all():
       post.slug = slugify(post.title)
       post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='bla-bla', unique_for_date=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs),
    ]
